### ISSUE TITLE
AMIs used by Existing VPC CloudFormation template don't allow some instance types

### ISSUE THREAD

**Issue by medavisjr** [aerospike/aws-cloudformation#25]
The AMIs currently used in the Existing VPC CloudFormation template don't allow certain instance types that are reported as enabled for use in the [AWS Marketplace page for Aerospike Database Enterprise Edition](https://aws.amazon.com/marketplace/pp/prodview-ouzvxjdgfsa64).

At least these instance types are not enabled on the AMI, maybe more:

- c3
- c4
- c5
- i2
- i3
- i3en

The problem seems to be that the AWS Marketplace CloudFormation template for "Aerospike Database Enterprise Edition" points to the AMIs for "Aerospike Database" instead of its own AMIs. You can see this in the AMIs in the "Aerospike Database Enterprise Edition" CF template:

```
Mappings:
  AWSAMIRegionMap:
    AMI:
      AEROSPIKEAMI: aerospike-amazonlinux2-20220508100353
    us-east-1:
      AEROSPIKEAMI: ami-05f5709c7c092d892
    us-east-2:
      AEROSPIKEAMI: ami-0ded916282885082d
    us-west-1:
      AEROSPIKEAMI: ami-0d3b55865039748fd
[...]
```

`us-east-1` mapping uses `ami-05f5709c7c092d892` when it should be using `ami-021f94397f9b7296a`, from what I can tell.

This results in the below error in the ASG that the CloudFormation template creates if the user doesn't happen to choose an instance type that's supported by "Aerospike Database" Marketplace's AMI image.

In this case, I was trying to launch an `i3en` instance type using the CloudFormation template, and it failed because the Marketplace AMI being used doesn't support it.

>Launching a new EC2 instance. Status Reason: The instance configuration for this AWS Marketplace product is not supported. Please see the AWS Marketplace site for more information about supported instance types, regions, and operating systems. Launching EC2 instance failed.

This whole kerfluffle with the Marketplace products also causes a separate but closely related problem in that the ASG can't even attempt to launch the instance until the account subscribes to the "Aerospike Database" Marketplace product, even if they're already subscribed to the "Aerospike Database Enterprise Edition" Marketplace product:

> Launching a new EC2 instance. Status Reason: In order to use this AWS Marketplace product you need to accept terms and subscribe. To do so please visit https://aws.amazon.com/marketplace/pp?sku=ekg8c7lctclzvufhp0gzzl8ro. Launching EC2 instance failed.
